// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyxxzxxezybffsidgqfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5eHh6eHhlenliZmZzaWRncWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDkyNjUsImV4cCI6MjA1NTE4NTI2NX0.yFldGw0UC8tHAByrccDrl6V9xca15UHwwCLj1qCyROQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);